### PR TITLE
add mistral

### PR DESCRIPTION
**Pull request by dkupnicki**

### CODE REVIEW

**Comment by MarcelWilnicki** [comment]
When running the model according to readme, in docker image amperecomputingai/pytorch:latest, I encounter such an issue: 

<details>
<summary>Click to expand terminal output :)</summary>


```root@rtp-mq1-06-jade:/ampere/aml/natural_language_processing/text_generation/mistral_instruct# ALPACA_DATASET_PATH=/ampere/aml/natural_language_processing/text_generation/mistral_instruct/alpaca_data.json python run.py
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:03<00:00,  1.22s/it]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
 
CAUTION: Remember to compile your model with torch.jit / torch.compile for Ampere optimizations to work.
 
CAUTION: KernelPageSize is 4 kB, consider using 64k pages.
 
CAUTION: Transparent_hugepage is set to never. Consider using 'always'.
 
Intraop parallelism set to 16 threads
 
 
Running with PyTorch
 
  0%|                                                                                                                                | 0/60 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/ampere/aml/natural_language_processing/text_generation/mistral_instruct/run.py", line 53, in <module>
    main()
  File "/ampere/aml/natural_language_processing/text_generation/mistral_instruct/run.py", line 49, in main
    run_pytorch_fp32(**vars(parser.parse()))
  File "/ampere/aml/natural_language_processing/text_generation/mistral_instruct/run.py", line 40, in run_pytorch_fp32
    return run_pytorch(num_runs, timeout, dataset_path, disable_jit_freeze, **kwargs)
  File "/ampere/aml/natural_language_processing/text_generation/mistral_instruct/run.py", line 36, in run_pytorch
    return run_model(run_single_pass, runner, dataset, 1, num_runs, timeout)
  File "/ampere/aml/utils/benchmark.py", line 229, in run_model
    single_pass_func(runner, dataset)
  File "/ampere/aml/natural_language_processing/text_generation/mistral_instruct/run.py", line 15, in run_single_pass
    input_array = dataset.get_input_array()
  File "/ampere/aml/utils/nlp/alpaca_instruct.py", line 42, in get_input_array
    return self.data[self.__current_sample]
KeyError: 0
  0%|                                                                                                                                | 0/60 [00:00<?, ?it/s]
```

**Comment by jan-grzybek-ampere** [comment]
@dkupnicki any updates on the issue Marcel seen?

**Comment by dkupnicki** [comment]
I don't see this issue when running normally, but I was able to get this error message when I manually corrupted the dataset file. Maybe try redownloading it and see if it helps?

**Comment by MarcelWilnicki** [comment]
requirements:

transformers==4.36.0

change the alpaca_data.json link to: (or add as an optional)
https://raw.githubusercontent.com/tatsu-lab/stanford_alpaca/main/alpaca_data.json

**Pull request merged**
