### PR TITLE
fix args parser 

### PR DESCRIPTION
**Pull request by MarcelWilnicki**

### CODE REVIEW

**Comment by dkupnicki** [comment]
Why is the model being removed?

**Comment by MarcelWilnicki** [comment]
the model that we have in our resources is corrupted and can't be run.

**Review by jan-grzybek-ampere — APPROVED** [review]

**Comment by dkupnicki** [comment]
The link in the Readme seems broken, but we have a copy of this model in our S3 and it seems to work fine

Screenshot 2023-11-17 at 11 51 11

**Comment by jan-grzybek-ampere** [comment]
@MarcelWilnicki can you please verify Daniel's claims? Can this model be run with latest ort-aio?

**Comment by MarcelWilnicki** [comment]
I know what was the issue here, the model supplied in the README is corrupt (dropbox), but the model in S3 works fine.

**Comment by jan-grzybek-ampere** [comment]
Fixed by other PR.

**Pull request closed without merging**
