### PR TITLE
add efficientdet

### PR DESCRIPTION
**Pull request by dkupnicki**
The model will not work with our release docker, but it works fine with the latest fixes.

### CODE REVIEW

**Comment by jan-grzybek-ampere** [comment]
@smamindl can you please have a quick look and do a review? It's a a good example of addition of a network to AML with substantial reuse of existing functions.

**Comment by jan-grzybek-ampere** [comment]
@smamindl have you been able to run the model with Daniel's script? Is the code looking ok?

**Review by jan-grzybek-ampere — APPROVED** [review]
LGTM

**Comment by smamindl** [comment]
> @smamindl have you been able to run the model with Daniel's script? Is the code looking ok?

Hi @jan-grzybek-ampere , The code looks good and I was able to run his script. One suggestion though, @dkupnicki can you update the README reagrding the dataset where you use images and annotations from AWS S3. Thanks!

**Pull request merged**
