### PR TITLE
Fix retinanet model for pytorch 2.0

### PR DESCRIPTION
**Pull request by mwalenciak-ampere**

### CODE REVIEW

**Comment by mwalenciak-ampere** [comment]
> I think it's worth considering to leave the old model, too, in addition to adding this version. Even if the old one doesn't work with torch.compile, it should still work with jit.script and it's a model used in MLPerf benchmarks. Unless the only significant difference between the two models is the dataset they use, in which case I guess it's fine to just have the Torchvision one.

So I guess the new model should get a different name? What would it be?

**Comment by dkupnicki** [comment]
I suggest either renaming the old model to `retinanet_mlperf` or naming the new one `retinanet_torchvision` (or maybe even use new names for both)

**Review by jan-grzybek-ampere — COMMENTED** [review]
@dkupnicki do both models differ aside from torch.compile() call in runner script? Do you think we should treat them as two separate models or rather have them under one single runner able to do both torch.jit or torch.compile (or neither of them)? If these are the same models just differently run, then I think having two scripts in two directories unnecessarily confuses user as to which one to use.

**Comment by kkontny** [comment]
> @dkupnicki do both models differ aside from torch.compile() call in runner script? Do you think we should treat them as two separate models or rather have them under one single runner able to do both torch.jit or torch.compile (or neither of them)? If these are the same models just differently run, then I think having two scripts in two directories unnecessarily confuses user as to which one to use.

@jan-grzybek-ampere No, torchvision RetinaNet is based on ResNet, not on ResNext (like in MLPerf). The difficulty with MlPerf model is that, we load TorchScripted version, which is not compatible with `torch.compile`.

**Review by jan-grzybek-ampere — APPROVED** [review]

**Pull request merged**
